apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  labels:
    app: insecure-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
