apiVersion: v1
kind: Service
metadata:
  name: insecure-registry
  labels:
    app: insecure-registry
spec:
  type: ClusterIP
  selector:
    app: insecure-registry
  ports:
    - name: registry-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
